baseURL = "https://www.ftvkyo.me/"
languageCode = "en-us"
title = "ftvkyo"
theme = "ftvkyo-hugo-theme"


# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"


[params]
  tagline = "pretty much Andrei"
  footer = "Made with [Hugo](https://gohugo.io/). Content and styles by [me](/about/)."

  dateFormat = "2006-01-02"

  #body_link_color = "#1e6bff"


# Enable raw HTML in the pages.
[markup.goldmark.renderer]
  unsafe = true


[taxonomies]
  tag = "tags"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 20
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 40
