baseURL = "https://www.ftvkyo.me/"
languageCode = "en-us"
title = "ftvkyo"


[params]
  fullName = "Andrei Stepanenko"
  footer = "Made with [Hugo](https://gohugo.io/). Content and styles by [me](/about/)."

  dateFormat = "Jan 2, 2006"


[markup.highlight]
  style = "onedark"
  guessSyntax = true

# Enable raw HTML in the pages.
[markup.goldmark.renderer]
  unsafe = true


[taxonomies]
  tag = "tags"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 20
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 30
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 40
