baseURL = "https://www.ftvkyo.me/"
languageCode = "en-us"
title = "ftvkyo"


[params]
  fullName = "Andrei Stepanenko"
  footer = "Made with [Hugo](https://gohugo.io/). Content and styles by [me](/about/)."

  dateFormat = "Jan 2, 2006"


[taxonomies]
  tag = "tags"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 20
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 30
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 40


[markup]
  # Reference: https://gohugo.io/getting-started/configuration-markup/

  [markup.highlight]
    style = "onedark"
    guessSyntax = true

  [markup.goldmark]

    [markup.goldmark.renderer]
      # Enable raw HTML in the pages.
      unsafe = true

    [markup.goldmark.extensions.typographer]
      leftDoubleQuote = "&laquo;"
      rightDoubleQuote = "&raquo;"
