name: Deploy to ftvkyo.github.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Used by hugo for better sass (e.g. @use)
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: www.ftvkyo.me
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ftvkyo/ftvkyo.github.io
          publish_dir: ./public
          force_orphan: true  # Hide history
